version: '3.8'

services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: wadidbuser
      POSTGRES_PASSWORD: wadi1234
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080   # Interface Web
      - 1025:1025   # SMTP
    networks:
      - spring-demo
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

networks:
  spring-demo:
    driver: bridge